var  namyFullNameme;
console.log(namyFullNameme);
var myFullName="Dada Bhoge";
console.log(myFullName);
var myFullName= "Dada Sunil Bhoge";
console.log(myFullName);
var myLove="I Love Only JS";
console.log(myLove);
var firstName="Dada";
console.log("FisrtName :",firstName);
var lastName="Bhoge";
console.log("LastName :",lastName);
var age="25";
console.log("MyAge :",age);
var address="A/P- Sade Tal - Karmala Dist - Solapur";
console.log("Address :",address);
var pinCode="413251";
console.log("PinCOde :",pinCode);
var gender="Male";
console.log("Gender :",gender);
var isMarried="UnMarried";
console.log("IsMarried :",isMarried);
