console.log("><><><><><>< Assignment No 02 ><><><><><>");
console.log("*-*-Step I-*-*");
var bankName;
console.log("Before Initialization");
console.log("Bank Name : unDefined",",","DataType :",bankName);
bankName="SBI Bank";
console.log("After Initialization");
console.log("Bank Name : SBI Bank",",","Data Type :",typeof bankName);
console.log("*-*-Step II-*-*");
var marks='90%';
console.log("Mark :",marks,",","Type :",typeof marks);
console.log("*-*-Step III-*-*");
var isWorking;
console.log("Before Initialization");
console.log("IsWorking :",isWorking,",","Type : ",typeof isWorking );
isWorking=true;
console.log("After Initialization");
console.log("IsWorking :",isWorking,",","Type : ",typeof isWorking);
console.log("*-*-Step IX-*-*");
var totalCount="Hundred and Seven";
console.log("TotalCount :",totalCount,",","Type :",typeof totalCount);
var totalCount=107;
console.log("TotalCount :",totalCount,",","Type :",typeof totalCount);
